<a href="https://colab.research.google.com/github/MarcelaMosino/hacking-civico/blob/master/tarea/03-exploracion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="http://codeandomexico.org/resources/img/codeandomexico.png" width="500" alt="Codeando México"><br>
<a href="http://www.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/website-CodeandoMexico-00D88E.svg"></a>
<a href="http://slack.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/slack-CodeandoMexico-EC0E4F.svg"></a>
</p>
<!-- __ -->

# Curso de Datos Abiertos y Hacking Cívico

Este curso tiene como objetivo habilitar las capacidades de la ciudadanía y los servidores públicos en el uso y generación de datos abiertos para el bien común. Puedes encontrar más información [aquí](https://github.com/CodeandoMexico/hacking-civico).

# Exploración de datos: COVID-19 en México

En este cuaderno aprenderemos algunas bases de exploración de datos. Los datos a utilizar son los datos abiertos sobre COVID-19 en México, los cuales pueden ser accedidos directamente desde el portal: https://www.gob.mx/salud/documentos/datos-abiertos-152127

Del portal de datos abiertos podemos encontrar dos enlaces, uno para descargar el conjunto de datos y otro para descargar el diccionario; así que podemos automatizar el proceso de descarga y descompresión de la información.

Para obtener los datos, sólo basta que ejecutes la siguiente línea de código, que contiene el comando de descarga de la información.

In [ ]:
# Para descargar el conjunto de datos
!wget http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip

# Para descargar el diccionario de los datos
!wget http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip

# Descomprimimos ambas carpetas y movemos archivos
!unzip datos_abiertos_covid19.zip
!unzip diccionario_datos_covid19.zip
!mv ./diccionario_datos_covid19/*.xlsx .
!mv *COVID19MEXICO.csv COVID19MEXICO.csv

# Eliminamos las carpetas comprimidas
!rm -rf diccionario_datos_covid19
!rm datos_abiertos_covid19.zip
!rm diccionario_datos_covid19.zip

--2020-09-11 00:26:04--  http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip
Resolving datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)... 187.210.186.146
Connecting to datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)|187.210.186.146|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31038383 (30M) [application/x-zip-compressed]
Saving to: ‘datos_abiertos_covid19.zip’

datos_abiertos_covi 100%[===================>]  29.60M  1.21MB/s    in 32s

2020-09-11 00:26:37 (958 KB/s) - ‘datos_abiertos_covid19.zip’ saved [31038383/31038383]

--2020-09-11 00:26:37--  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Resolving epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)... 187.191.75.207
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:27:10--  (try: 2)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:27:43--  (try: 3)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:28:18--  (try: 4)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:28:54--  (try: 5)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:29:31--  (try: 6)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:30:09--  (try: 7)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:30:47--  (try: 8)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:31:27--  (try: 9)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:32:08--  (try:10)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:32:50--  (try:11)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:33:32--  (try:12)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:34:14--  (try:13)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:34:56--  (try:14)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... failed: Connection timed out.
Retrying.

--2020-09-11 00:35:38--  (try:15)  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... ^C
Archive:  datos_abiertos_covid19.zip
  inflating: 200909COVID19MEXICO.csv
unzip:  cannot find or open diccionario_datos_covid19.zip, diccionario_datos_covid19.zip.zip or diccionario_datos_covid19.zip.ZIP.
mv: cannot stat './diccionario_datos_covid19/*.xlsx': No such file or directory
rm: cannot remove 'diccionario_datos_covid19.zip': No such file or directory

Hasta este punto, si abres la barra lateral izaquiera, deberías ser capaz de encontrar los datos:

- `COVID19MEXICO.csv`
- `Catalogos_0412.xlsx`
- `Descriptores_0419.xlsx`

👈🏼

## Carga

Ahora que tenemos los datos, procederemos a cargarlos. Para cargar los datos, primero importaremos algunos paquetes de Python, pues su funcionalidad nos será muy util.

In [ ]:
import statistics

import pandas as pd
import numpy as np

In [ ]:
# Especificamos el nombre del archivo por abrir
nombre_archivo = 'COVID19MEXICO.csv'

# Utilizamos la función de Pandas para cargar un archivo CSV
data = pd.read_csv(nombre_archivo, encoding='latin-1')

Mostramos la cabeza (primeros elementos del archivo).

In [ ]:
data.head()

  FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  ...  PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI
0          2020-09-09      0fa3df       2  ...            MÃ©xico           99   97
1          2020-09-09      04b5e9       2  ...            MÃ©xico           99    2
2          2020-09-09      005e0d       2  ...            MÃ©xico           99   97
3          2020-09-09      12667d       2  ...            MÃ©xico           99   97
4          2020-09-09      0fdf68       2  ...            MÃ©xico           99   97

[5 rows x 35 columns]

Ahora procedemos a cargar el archivo con los descriptores.

In [ ]:
nombre_diccionario = 'Descriptores_0419.xlsx'
diccionario = pd.read_excel(nombre_diccionario)

In [ ]:
diccionario

    Nº  ...                                   FORMATO O FUENTE
0    1  ...                                         AAAA-MM-DD
1    2  ...                                             TEXTO
2    3  ...  CATÁLOGO: ORIGEN                              ...
3    4  ...  CATÁLOGO: SECTOR                              ...
4    5  ...                                CATALÓGO: ENTIDADES
5    6  ...       CATÁLOGO: SEXO
6    7  ...                                CATALÓGO: ENTIDADES
7    8  ...                                CATALÓGO: ENTIDADES
8    9  ...                               CATALÓGO: MUNICIPIOS
9   10  ...                           CATÁLOGO: TIPO_PACIENTE
10  11  ...                                         AAAA-MM-DD
11  12  ...                                         AAAA-MM-DD
12  13  ...                                         AAAA-MM-DD
13  14  ...  CATÁLOGO: SI_ NO                              ...
14  15  ...  CATÁLOGO: SI_ NO                              ...
15  16  ...                                   NÚMERICA EN AÑOS
16  17  ...                            CATÁLOGO: NACIONALIDAD
17  18  ...  CATÁLOGO: SI_ NO                              ...
18  19  ...  CATÁLOGO: SI_ NO                              ...
19  20  ...  CATÁLOGO: SI_ NO                              ...
20  21  ...  CATÁLOGO: SI_ NO                              ...
21  22  ...  CATÁLOGO: SI_ NO                              ...
22  23  ...  CATÁLOGO: SI_ NO                              ...
23  24  ...  CATÁLOGO: SI_ NO                              ...
24  25  ...  CATÁLOGO: SI_ NO                              ...
25  26  ...  CATÁLOGO: SI_ NO                              ...
26  27  ...  CATÁLOGO: SI_ NO                              ...
27  28  ...  CATÁLOGO: SI_ NO                              ...
28  29  ...  CATÁLOGO: SI_ NO                              ...
29  30  ...  CATÁLOGO: SI_ NO                              ...
30  31  ...                                CATÁLOGO: RESULTADO
31  32  ...  CATÁLOGO: SI_ NO                              ...
32  33  ...                               TEXTO, 99= SE IGNORA
33  34  ...                               TEXTO, 97= NO APLICA
34  35  ...  CATÁLOGO: SI_ NO                              ...

[35 rows x 4 columns]

Finalmente, cargamos el rachivo de catálogos.

In [ ]:
nombre_cat = 'Catalogos_0412.xlsx'
sheets = ['ORIGEN', 'SECTOR', 'SEXO', 'TIPO_PACIENTE', 'SI_NO', 'NACIONALIDAD', 'RESULTADO', 'de ENTIDADES', 'MUNICIPIOS']
catalogues = {}
for sheet in sheets:
  catalogue = pd.read_excel(nombre_cat, sheet_name='Catálogo ' + sheet)
  catalogue.columns = catalogue.columns.str.replace(' ', '_')
  catalogue.columns = catalogue.columns.str.replace('.', '')
  catalogue.columns = catalogue.columns.str.lower()
  new_catalogue = {sheet: catalogue}
  catalogues.update(new_catalogue)

In [ ]:
catalogues

{'MUNICIPIOS':       clave_municipio        municipio  clave_entidad
 0                   1   AGUASCALIENTES              1
 1                   2         ASIENTOS              1
 2                   3         CALVILLO              1
 3                   4            COSÍO              1
 4                   5      JESÚS MARÍA              1
 ...               ...              ...            ...
 2496              999  NO ESPECIFICADO             32
 2497              999  NO ESPECIFICADO             36
 2498              997        NO APLICA             97
 2499              998        SE IGNORA             98
 2500              999  NO ESPECIFICADO             99

 [2501 rows x 3 columns], 'NACIONALIDAD':    clave      descripción
 0      1         MEXICANA
 1      2       EXTRANJERA
 2     99  NO ESPECIFICADO, 'ORIGEN':    clave      descripción
 0      1            USMER
 1      2   FUERA DE USMER
 2     99  NO ESPECIFICADO, 'RESULTADO':   unnamed:_0              unnamed:_1
 0      CLAVE             DESCRIPCIÓN
 1          1     Positivo SARS-CoV-2
 2          2  No positivo SARS-CoV-2
 3          3     Resultado pendiente, 'SECTOR':     clave      descripción
 0       1        CRUZ ROJA
 1       2              DIF
 2       3          ESTATAL
 3       4             IMSS
 4       5   IMSS-BIENESTAR
 5       6           ISSSTE
 6       7        MUNICIPAL
 7       8            PEMEX
 8       9          PRIVADA
 9      10           SEDENA
 10     11            SEMAR
 11     12              SSA
 12     13    UNIVERSITARIO
 13     99  NO ESPECIFICADO, 'SEXO':    clave      descripción
 0      1            MUJER
 1      2           HOMBRE
 2     99  NO ESPECIFICADO, 'SI_NO':    clave      descripción
 0      1              SI
 1      2              NO
 2     97        NO APLICA
 3     98        SE IGNORA
 4     99  NO ESPECIFICADO, 'TIPO_PACIENTE':    clave      descripción
 0      1      AMBULATORIO
 1      2    HOSPITALIZADO
 2     99  NO ESPECIFICADO, 'de ENTIDADES':     clave_entidad               entidad_federativa abreviatura
 0               1                   AGUASCALIENTES          AS
 1               2                  BAJA CALIFORNIA          BC
 2               3              BAJA CALIFORNIA SUR          BS
 3               4                         CAMPECHE          CC
 4               5             COAHUILA DE ZARAGOZA          CL
 5               6                           COLIMA          CM
 6               7                          CHIAPAS          CS
 7               8                        CHIHUAHUA          CH
 8               9                 CIUDAD DE MÉXICO          DF
 9              10                          DURANGO          DG
 10             11                       GUANAJUATO          GT
 11             12                         GUERRERO          GR
 12             13                          HIDALGO          HG
 13             14                          JALISCO          JC
 14             15                           MÉXICO          MC
 15             16              MICHOACÁN DE OCAMPO          MN
 16             17                          MORELOS          MS
 17             18                          NAYARIT          NT
 18             19                       NUEVO LEÓN          NL
 19             20                           OAXACA          OC
 20             21                           PUEBLA          PL
 21             22                        QUERÉTARO          QT
 22             23                     QUINTANA ROO          QR
 23             24                  SAN LUIS POTOSÍ          SP
 24             25                          SINALOA          SL
 25             26                           SONORA          SR
 26             27                          TABASCO          TC
 27             28                       TAMAULIPAS          TS
 28             29                         TLAXCALA          TL
 29             30  VERACRUZ DE IGNACIO DE LA LLAVE          VZ
 30             31                          YUCATÁN          YN
 31             32                        ZACATECAS          ZS
 32             36         ESTADOS UNIDOS MEXICANOS         EUM
 33             97                        NO APLICA         NaN
 34             98                        SE IGNORA          SI
 35             99                  NO ESPECIFICADO          NE}

In [ ]:
catalogues['SEXO']

   clave      descripción
0      1            MUJER
1      2           HOMBRE
2     99  NO ESPECIFICADO

##Perfilamiento

###Descripción General

In [ ]:
# dimensión de los datos
print('Número de filas: {}'.format(data.shape[0]))
print('Número de columnas: {}'.format(data.shape[1]))

Número de filas: 1465693
Número de columnas: 35

In [ ]:
# columnas (variables)
data.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [ ]:
# limpieza del nombre de las columnas, remover espacios, carácteres especiales y pasar a minúsculas
data.columns = data.columns.str.replace(' ', '_')
data.columns = data.columns.str.replace('.', '')
data.columns = data.columns.str.lower()

In [ ]:
# calcular número de valores nulos por columna
for col in data.columns:
  print('Valores nulos en "{}": {}'.format(col,data[col].isna().sum()))

Valores nulos en "fecha_actualizacion": 0
Valores nulos en "id_registro": 0
Valores nulos en "origen": 0
Valores nulos en "sector": 0
Valores nulos en "entidad_um": 0
Valores nulos en "sexo": 0
Valores nulos en "entidad_nac": 0
Valores nulos en "entidad_res": 0
Valores nulos en "municipio_res": 0
Valores nulos en "tipo_paciente": 0
Valores nulos en "fecha_ingreso": 0
Valores nulos en "fecha_sintomas": 0
Valores nulos en "fecha_def": 0
Valores nulos en "intubado": 0
Valores nulos en "neumonia": 0
Valores nulos en "edad": 0
Valores nulos en "nacionalidad": 0
Valores nulos en "embarazo": 0
Valores nulos en "habla_lengua_indig": 0
Valores nulos en "diabetes": 0
Valores nulos en "epoc": 0
Valores nulos en "asma": 0
Valores nulos en "inmusupr": 0
Valores nulos en "hipertension": 0
Valores nulos en "otra_com": 0
Valores nulos en "cardiovascular": 0
Valores nulos en "obesidad": 0
Valores nulos en "renal_cronica": 0
Valores nulos en "tabaquismo": 0
Valores nulos en "otro_caso": 0
Valores nulos en "resultado": 0
Valores nulos en "migrante": 0
Valores nulos en "pais_nacionalidad": 0
Valores nulos en "pais_origen": 0
Valores nulos en "uci": 0

In [ ]:
# tipos de datos
data.dtypes

fecha_actualizacion    object
id_registro            object
origen                  int64
sector                  int64
entidad_um              int64
sexo                    int64
entidad_nac             int64
entidad_res             int64
municipio_res           int64
tipo_paciente           int64
fecha_ingreso          object
fecha_sintomas         object
fecha_def              object
intubado                int64
neumonia                int64
edad                    int64
nacionalidad            int64
embarazo                int64
habla_lengua_indig      int64
diabetes                int64
epoc                    int64
asma                    int64
inmusupr                int64
hipertension            int64
otra_com                int64
cardiovascular          int64
obesidad                int64
renal_cronica           int64
tabaquismo              int64
otro_caso               int64
resultado               int64
migrante                int64
pais_nacionalidad      object
pais_origen            object
uci                     int64
dtype: object

###Limpieza

In [ ]:
# convertimos a fecha algunas columnas
def cast_datetime_cols(df):
    timestamp_cols = [col for col in df.columns if "fecha" in col]
    df[timestamp_cols] = df[timestamp_cols].apply(lambda date_col: pd.to_datetime(date_col, errors="coerce"), axis=0)
    return df

data = cast_datetime_cols(data)

In [ ]:
data.head()

  fecha_actualizacion id_registro  origen  ...  pais_nacionalidad  pais_origen  uci
0          2020-09-09      0fa3df       2  ...            MÃ©xico           99   97
1          2020-09-09      04b5e9       2  ...            MÃ©xico           99    2
2          2020-09-09      005e0d       2  ...            MÃ©xico           99   97
3          2020-09-09      12667d       2  ...            MÃ©xico           99   97
4          2020-09-09      0fdf68       2  ...            MÃ©xico           99   97

[5 rows x 35 columns]

In [ ]:
# unimos los datos con los catalogos para tener mejor entendimiento de ellos
data = (
    # unimos con el catálogo MUNICIPIOS y ENTIDADES
    data.merge(catalogues['de ENTIDADES'], how='left', left_on='entidad_res', right_on='clave_entidad').
    drop(columns=['entidad_res', 'abreviatura']).
    rename(columns={'entidad_federativa':'entidad_res'}).
    merge(catalogues['MUNICIPIOS'], how='left', left_on=['clave_entidad','municipio_res'], right_on=['clave_entidad','clave_municipio']).
    drop(columns=['municipio_res', 'clave_entidad', 'clave_municipio']).
    rename(columns={'municipio':'municipio_res'})
)

In [ ]:
# unimos con el catálogo de ENTIDADES
entidades_cols = [col for col in data.columns if "entidad" in col and col != 'entidad_res']
for col in entidades_cols:
    data = (
        data.merge(catalogues['de ENTIDADES'], how='left', left_on=col, right_on='clave_entidad').
        drop(columns=[col, 'abreviatura', 'clave_entidad']).
        rename(columns={'entidad_federativa':col})
    )

In [ ]:
# unimos con el catálogo SI_NO
sino_cols = ['intubado', 'neumonia', 'embarazo', 'habla_lengua_indig', 'diabetes', 'epoc', 'asma', 'inmusupr',
             'hipertension', 'otra_com', 'cardiovascular', 'obesidad', 'renal_cronica', 'tabaquismo', 
             'otro_caso', 'migrante', 'uci']
for col in sino_cols:
    data = (
        data.merge(catalogues['SI_NO'], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripción':col})
    )

> **Nota:**
>
> Si ejecutaste una versión previa del cuaderno, notarás que en la siguiente sección aparecía un error. A continuación dejamos como un pequeño paréntesis un poco más de limpieza sobre el cuaderno.

1. Corregimos el nombre de las columnas:

In [ ]:
catalogues['RESULTADO'].columns

Index(['unnamed:_0', 'unnamed:_1'], dtype='object')

In [ ]:
catalogues['RESULTADO'].columns = ['clave', 'descripción']
catalogues['RESULTADO'].columns

Index(['clave', 'descripción'], dtype='object')

2. Removemos la (primera) fila que no nos es útil.

In [ ]:
catalogues['RESULTADO'] = catalogues['RESULTADO'].drop(index=0)

3. Convertimos el tipo de dato.

In [ ]:
catalogues['RESULTADO']['clave'] = catalogues['RESULTADO']['clave'].astype(int)

> Fin del paréntesis. Hasta esta sección, esta parte de limpieza permite continuar con el proceso de manera normal.

In [ ]:
# unimos otras columnnas que comparten lógica
other_cols = ['origen', 'sector', 'sexo', 'tipo_paciente', 'nacionalidad', 'resultado']
for col, cat in zip(other_cols, [x.upper() for x in other_cols]):
    data = (
        data.merge(catalogues[cat], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripción':col})
    )

In [ ]:
# creamos algunas variables que podrían ser útiles después
data['defuncion'] = ~data.fecha_def.isna()
data['mes_def'] = data.fecha_def.dt.month
data['año_def'] = data.fecha_def.dt.year
data['mes_ingreso'] = data.fecha_ingreso.dt.month
data['año_ingreso'] = data.fecha_ingreso.dt.year

In [ ]:
data.head()

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-09      0fa3df  ...           6        2020
1          2020-09-09      04b5e9  ...           4        2020
2          2020-09-09      005e0d  ...           4        2020
3          2020-09-09      12667d  ...           3        2020
4          2020-09-09      0fdf68  ...           4        2020

[5 rows x 40 columns]

###Filtros

**Distintas formas de filtrar lo mismo**

In [ ]:
# usando query
data.query('nacionalidad == "MEXICANA"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-09      0fa3df  ...           6        2020
1          2020-09-09      04b5e9  ...           4        2020

[2 rows x 40 columns]

In [ ]:
# haciendo referencia a la columna como índice
data[data['nacionalidad'] == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-09      0fa3df  ...           6        2020
1          2020-09-09      04b5e9  ...           4        2020

[2 rows x 40 columns]

In [ ]:
# seleccionando directamente la columna que queremos filtrar
data[data.nacionalidad == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
0          2020-09-09      0fa3df  ...           6        2020
1          2020-09-09      04b5e9  ...           4        2020

[2 rows x 40 columns]

**Filtrado múltiple**

In [ ]:
# usando query podemos poner en el string del query todas las condiciones que queramos
data.query('nacionalidad == "MEXICANA" & entidad_res == "CIUDAD DE MÉXICO"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
3          2020-09-09      12667d  ...           3        2020
4          2020-09-09      0fdf68  ...           4        2020

[2 rows x 40 columns]

In [ ]:
# usando el filtrado tradicional debemos encerrar en paréntesis cada condición que queremos que cumpla nuestro filtro
data[(data['nacionalidad'] == "MEXICANA") & (data.entidad_res == "CIUDAD DE MÉXICO")].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
3          2020-09-09      12667d  ...           3        2020
4          2020-09-09      0fdf68  ...           4        2020

[2 rows x 40 columns]

###Resúmenes

In [ ]:
# una columna, una métrica
data.groupby('sexo').edad.mean()

sexo
HOMBRE    42.729066
MUJER     41.681075
Name: edad, dtype: float64

In [ ]:
# una columna, varias métricas
data.groupby('sexo').agg({'edad': ['min','mean','max']})

       edad
        min       mean  max
sexo
HOMBRE    0  42.729066  120
MUJER     0  41.681075  120

In [ ]:
# varias columnas, una métrica
data.groupby('sexo').agg({'edad': 'mean', 'mes_ingreso': 'mean', 'mes_def': 'mean'})

             edad  mes_ingreso   mes_def
sexo
HOMBRE  42.729066     6.663729  6.453922
MUJER   41.681075     6.736495  6.521498

In [ ]:
# varias columnas, varias métricas
data.groupby('sexo').agg({'edad': ['min','mean','max'], 'mes_ingreso': ['min','mean','max'], 'mes_def': ['min','mean','max']})

       edad                 mes_ingreso               mes_def
        min       mean  max         min      mean max     min      mean  max
sexo
HOMBRE    0  42.729066  120           1  6.663729   9     1.0  6.453922  9.0
MUJER     0  41.681075  120           1  6.736495   9     1.0  6.521498  9.0

###Descripción por Tipo

In [ ]:
# Filtrar por tipos generales (categóricas y numéricas)
numerical = data.select_dtypes(include='number')
categorical = data.select_dtypes(include=['object', 'bool', 'category', 'datetime64[ns]'])

In [ ]:
numerical.head()

   edad  mes_def  año_def  mes_ingreso  año_ingreso
0    48      NaN      NaN            6         2020
1    26      4.0   2020.0            4         2020
2    40      NaN      NaN            4         2020
3    33      NaN      NaN            3         2020
4    29      NaN      NaN            4         2020

In [ ]:
categorical.head()

  fecha_actualizacion id_registro  ...            resultado defuncion
0          2020-09-09      0fa3df  ...  Positivo SARS-CoV-2     False
1          2020-09-09      04b5e9  ...  Positivo SARS-CoV-2      True
2          2020-09-09      005e0d  ...  Positivo SARS-CoV-2     False
3          2020-09-09      12667d  ...  Positivo SARS-CoV-2     False
4          2020-09-09      0fdf68  ...  Positivo SARS-CoV-2     False

[5 rows x 35 columns]

In [ ]:
# para conocer todos los tipo de datos
?data.select_dtypes

####Categóricas

In [ ]:
# Cardinalidad - Valores únicos por columna
for col in categorical.columns:
  print('Valores únicos en "{}": {}'.format(col,categorical[col].nunique()))

Valores únicos en "fecha_actualizacion": 1
Valores únicos en "id_registro": 1465693
Valores únicos en "fecha_ingreso": 253
Valores únicos en "fecha_sintomas": 253
Valores únicos en "fecha_def": 198
Valores únicos en "pais_nacionalidad": 119
Valores únicos en "pais_origen": 77
Valores únicos en "entidad_res": 32
Valores únicos en "municipio_res": 2162
Valores únicos en "entidad_um": 32
Valores únicos en "entidad_nac": 33
Valores únicos en "intubado": 4
Valores únicos en "neumonia": 3
Valores únicos en "embarazo": 4
Valores únicos en "habla_lengua_indig": 3
Valores únicos en "diabetes": 3
Valores únicos en "epoc": 3
Valores únicos en "asma": 3
Valores únicos en "inmusupr": 3
Valores únicos en "hipertension": 3
Valores únicos en "otra_com": 3
Valores únicos en "cardiovascular": 3
Valores únicos en "obesidad": 3
Valores únicos en "renal_cronica": 3
Valores únicos en "tabaquismo": 3
Valores únicos en "otro_caso": 3
Valores únicos en "migrante": 3
Valores únicos en "uci": 4
Valores únicos en "origen": 2
Valores únicos en "sector": 14
Valores únicos en "sexo": 2
Valores únicos en "tipo_paciente": 2
Valores únicos en "nacionalidad": 2
Valores únicos en "resultado": 3
Valores únicos en "defuncion": 2

In [ ]:
# Unicidad - proporción de valores únicos por columna
total = data.shape[0]
for col in categorical.columns:
  print('Porcentaje de valores únicos en "{}": {}%'.format(col,round(categorical[col].nunique()/total*100,2)))

Porcentaje de valores únicos en "fecha_actualizacion": 0.0%
Porcentaje de valores únicos en "id_registro": 100.0%
Porcentaje de valores únicos en "fecha_ingreso": 0.02%
Porcentaje de valores únicos en "fecha_sintomas": 0.02%
Porcentaje de valores únicos en "fecha_def": 0.01%
Porcentaje de valores únicos en "pais_nacionalidad": 0.01%
Porcentaje de valores únicos en "pais_origen": 0.01%
Porcentaje de valores únicos en "entidad_res": 0.0%
Porcentaje de valores únicos en "municipio_res": 0.15%
Porcentaje de valores únicos en "entidad_um": 0.0%
Porcentaje de valores únicos en "entidad_nac": 0.0%
Porcentaje de valores únicos en "intubado": 0.0%
Porcentaje de valores únicos en "neumonia": 0.0%
Porcentaje de valores únicos en "embarazo": 0.0%
Porcentaje de valores únicos en "habla_lengua_indig": 0.0%
Porcentaje de valores únicos en "diabetes": 0.0%
Porcentaje de valores únicos en "epoc": 0.0%
Porcentaje de valores únicos en "asma": 0.0%
Porcentaje de valores únicos en "inmusupr": 0.0%
Porcentaje de valores únicos en "hipertension": 0.0%
Porcentaje de valores únicos en "otra_com": 0.0%
Porcentaje de valores únicos en "cardiovascular": 0.0%
Porcentaje de valores únicos en "obesidad": 0.0%
Porcentaje de valores únicos en "renal_cronica": 0.0%
Porcentaje de valores únicos en "tabaquismo": 0.0%
Porcentaje de valores únicos en "otro_caso": 0.0%
Porcentaje de valores únicos en "migrante": 0.0%
Porcentaje de valores únicos en "uci": 0.0%
Porcentaje de valores únicos en "origen": 0.0%
Porcentaje de valores únicos en "sector": 0.0%
Porcentaje de valores únicos en "sexo": 0.0%
Porcentaje de valores únicos en "tipo_paciente": 0.0%
Porcentaje de valores únicos en "nacionalidad": 0.0%
Porcentaje de valores únicos en "resultado": 0.0%
Porcentaje de valores únicos en "defuncion": 0.0%

In [ ]:
# Moda - valor que más se repite en cada columna excepto los indicadores únicos
for col in categorical.drop(columns='id_registro').columns:
  print('Valor más popular en "{}": {}'.format(col, statistics.mode(categorical[col])))

Valor más popular en "fecha_actualizacion": 2020-09-09 00:00:00
Valor más popular en "fecha_ingreso": 2020-07-20 00:00:00
Valor más popular en "fecha_sintomas": 2020-07-20 00:00:00
Valor más popular en "fecha_def": NaT
Valor más popular en "pais_nacionalidad": MÃ©xico
Valor más popular en "pais_origen": 99
Valor más popular en "entidad_res": CIUDAD DE MÉXICO
Valor más popular en "municipio_res": IZTAPALAPA
Valor más popular en "entidad_um": CIUDAD DE MÉXICO
Valor más popular en "entidad_nac": CIUDAD DE MÉXICO
Valor más popular en "intubado": NO APLICA
Valor más popular en "neumonia": NO
Valor más popular en "embarazo": NO
Valor más popular en "habla_lengua_indig": NO
Valor más popular en "diabetes": NO
Valor más popular en "epoc": NO
Valor más popular en "asma": NO
Valor más popular en "inmusupr": NO
Valor más popular en "hipertension": NO
Valor más popular en "otra_com": NO
Valor más popular en "cardiovascular": NO
Valor más popular en "obesidad": NO
Valor más popular en "renal_cronica": NO
Valor más popular en "tabaquismo": NO
Valor más popular en "otro_caso": SI
Valor más popular en "migrante": NO ESPECIFICADO
Valor más popular en "uci": NO APLICA
Valor más popular en "origen": FUERA DE USMER
Valor más popular en "sector": SSA
Valor más popular en "sexo": MUJER
Valor más popular en "tipo_paciente": AMBULATORIO
Valor más popular en "nacionalidad": MEXICANA
Valor más popular en "resultado": No positivo SARS-CoV-2
Valor más popular en "defuncion": False

####Numéricas

In [ ]:
numerical.describe()

               edad       mes_def  año_def   mes_ingreso  año_ingreso
count  1.465693e+06  88230.000000  88230.0  1.465693e+06    1465693.0
mean   4.219647e+01      6.478522   2020.0  6.700709e+00       2020.0
std    1.680455e+01      1.277680      0.0  1.360388e+00          0.0
min    0.000000e+00      1.000000   2020.0  1.000000e+00       2020.0
25%    3.000000e+01      6.000000   2020.0  6.000000e+00       2020.0
50%    4.100000e+01      7.000000   2020.0  7.000000e+00       2020.0
75%    5.300000e+01      7.000000   2020.0  8.000000e+00       2020.0
max    1.200000e+02      9.000000   2020.0  9.000000e+00       2020.0

##Análisis Exploratorio

En esta sección responderemos algunas preguntas sobre el set de datos usando las herramientas que hemos visto hasta ahora

In [ ]:
# ¿Cuántas pruebas por origen se realizan?
data.groupby('origen').id_registro.count()

origen
FUERA DE USMER    979065
USMER             486628
Name: id_registro, dtype: int64

In [ ]:
data.origen.value_counts()

FUERA DE USMER    979065
USMER             486628
Name: origen, dtype: int64

In [ ]:
# ¿Cuántas pruebas por sector se realizan?
data.sector.value_counts()

SSA                912162
IMSS               376524
ISSSTE              55449
PRIVADA             54262
ESTATAL             26622
PEMEX               12665
IMSS-BIENESTAR       9987
SEMAR                7641
SEDENA               7164
MUNICIPAL            1166
UNIVERSITARIO         988
DIF                   835
CRUZ ROJA             220
NO ESPECIFICADO         8
Name: sector, dtype: int64

In [ ]:
# ¿Cuántos pacientes por sexo tenemos?
data.sexo.value_counts()

MUJER     744869
HOMBRE    720824
Name: sexo, dtype: int64

In [ ]:
# ¿Cuál es la proporción de los pacientes por sexo?
data.sexo.value_counts(normalize=True)

MUJER     0.508203
HOMBRE    0.491797
Name: sexo, dtype: float64

In [ ]:
# ¿Cuál es la proporción de resultados de las pruebas?
data.resultado.value_counts(normalize=True)

No positivo SARS-CoV-2    0.501230
Positivo SARS-CoV-2       0.441775
Resultado pendiente       0.056995
Name: resultado, dtype: float64

In [ ]:
# ¿Cuántas pruebas positivas tenemos en el set?
data[data.resultado == 'Positivo SARS-CoV-2'].id_registro.count()

647507

In [ ]:
# ¿Cuántos casos positivos tenemos por mes?
data[data.resultado == 'Positivo SARS-CoV-2'].mes_ingreso.value_counts().sort_index()

1         2
2         8
3      2530
4     26562
5     86513
6    152882
7    199172
8    154813
9     25025
Name: mes_ingreso, dtype: int64

In [ ]:
# ¿Cuál es el resultado de las pruebas por sexo?
data.groupby(['sexo','resultado'])['id_registro'].count()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    341708
        Positivo SARS-CoV-2       338337
        Resultado pendiente        40779
MUJER   No positivo SARS-CoV-2    392941
        Positivo SARS-CoV-2       309170
        Resultado pendiente        42758
Name: id_registro, dtype: int64

In [ ]:
data.groupby('sexo').resultado.value_counts()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    341708
        Positivo SARS-CoV-2       338337
        Resultado pendiente        40779
MUJER   No positivo SARS-CoV-2    392941
        Positivo SARS-CoV-2       309170
        Resultado pendiente        42758
Name: resultado, dtype: int64

In [ ]:
# ¿Qué proporción de resultados de pruebas tenemos por sexo?
data.groupby('sexo').resultado.value_counts(normalize=True)

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    0.474052
        Positivo SARS-CoV-2       0.469375
        Resultado pendiente       0.056573
MUJER   No positivo SARS-CoV-2    0.527530
        Positivo SARS-CoV-2       0.415066
        Resultado pendiente       0.057403
Name: resultado, dtype: float64

In [ ]:
# ¿Cuál es la edad de los pacientes por sexo?
data.groupby('sexo').edad.describe()

           count       mean        std  min   25%   50%   75%    max
sexo
HOMBRE  720824.0  42.729066  17.120749  0.0  30.0  41.0  54.0  120.0
MUJER   744869.0  41.681075  16.476415  0.0  30.0  40.0  52.0  120.0

In [ ]:
def q25(x):
  return x.quantile(0.25)

def q75(x):
  return x.quantile(0.75)

data.groupby('sexo').agg({'edad': ['min', q25, 'median', q75, 'max']})

       edad
        min q25 median q75  max
sexo
HOMBRE    0  30     41  54  120
MUJER     0  30     40  52  120

In [ ]:
# ¿Cuál es la edad de los pacientes dependiendo de si son intubados o no?
data.groupby('intubado').edad.describe()

                     count       mean        std  min   25%   50%   75%    max
intubado
NO                217550.0  53.301007  19.651220  0.0  42.0  55.0  67.0  118.0
NO APLICA        1208690.0  39.710740  15.062265  0.0  29.0  38.0  49.0  120.0
NO ESPECIFICADO      190.0  53.763158  17.176387  0.0  42.0  56.5  65.0   92.0
SI                 39263.0  57.134045  17.868686  0.0  48.0  59.0  69.0  108.0

In [ ]:
data.groupby('intubado').agg({'edad': ['min', q25, 'median', q75, 'max']})

                edad
                 min q25 median q75  max
intubado
NO                 0  42   55.0  67  118
NO APLICA          0  29   38.0  49  120
NO ESPECIFICADO    0  42   56.5  65   92
SI                 0  48   59.0  69  108

In [ ]:
# ¿Cuál es la edad máxima y cuál es la mínima de los pacientes fallecidos?
edad_def_max = data[data.defuncion].edad.max()
data[data.defuncion & (data.edad == edad_def_max)]

       fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
562321          2020-09-09      1b7b20  ...           5        2020

[1 rows x 40 columns]

In [ ]:
edad_def_min = data[data.defuncion].edad.min()
data[data.defuncion & (data.edad == edad_def_min)]

        fecha_actualizacion id_registro  ... mes_ingreso año_ingreso
7175             2020-09-09      05b7c8  ...           5        2020
13794            2020-09-09      083c34  ...           5        2020
29407            2020-09-09      02f8e2  ...           5        2020
41314            2020-09-09      014b5d  ...           5        2020
46447            2020-09-09      1c724e  ...           4        2020
...                     ...         ...  ...         ...         ...
1397250          2020-09-09      0860f4  ...           6        2020
1428176          2020-09-09      1e94e4  ...           8        2020
1436124          2020-09-09      00f39c  ...           7        2020
1444409          2020-09-09      07cf0b  ...           8        2020
1464495          2020-09-09      3b8095  ...           9        2020

[246 rows x 40 columns]

In [ ]:
# ¿Cuál es la edad de los pacientes que fallecen?
data.groupby('defuncion').edad.describe()

               count       mean        std  min   25%   50%   75%    max
defuncion
False      1377463.0  40.935601  16.101409  0.0  29.0  40.0  51.0  120.0
True         88230.0  61.881458  15.208669  0.0  53.0  63.0  72.0  109.0

In [ ]:
# ¿Cuántas defunciones tenemos por mes?
data[data.defuncion].mes_def.value_counts().sort_index()

1.0        6
2.0       12
3.0      232
4.0     5291
5.0    16085
6.0    21410
7.0    23707
8.0    18507
9.0     2980
Name: mes_def, dtype: int64

In [ ]:
# ¿Cuál es la proporción de diábeticos para las defunciones?
data.groupby('diabetes').defuncion.value_counts(normalize=True)

diabetes   defuncion
NO         False        0.957743
           True         0.042257
SE IGNORA  False        0.872660
           True         0.127340
SI         False        0.812988
           True         0.187012
Name: defuncion, dtype: float64

In [ ]:
# ¿Cuál es la proporción de asmáticos para las defunciones?
data.groupby('asma').defuncion.value_counts(normalize=True)

asma       defuncion
NO         False        0.939472
           True         0.060528
SE IGNORA  False        0.865169
           True         0.134831
SI         False        0.957717
           True         0.042283
Name: defuncion, dtype: float64

## COMIENZA MI PROPIA EXPLORACIÓN
_______________________________________________________
Para poder responder a las preguntas, corrí todos los bloques de el archivo del notebook pre-existente. Me basé en los comandos de los ejemplos para poder hacer una especie de consultas.

*¿Tienen los pacientes con hipertensión un riesgo más alto de defunción?*
> Para ésto, busqué la relación entre los pacientes con hipertensión y los muertos. Lo que resultó en que sólo el 16 porciento de los pacientes con hipertensión, murieron.
Además, para codificarlo, bastó con agrupar por 'hipertension' y luego contar los valores en formato de porcentaje.

In [ ]:
### ¿Tienen los pacientes con hipertensión un riesgo más alto de defunción?
### Buscar pacientes con hipertensión muertos
data.groupby('hipertension').defuncion.value_counts(normalize=True)

hipertension  defuncion
NO            False        0.960364
              True         0.039636
SE IGNORA     False        0.872925
              True         0.127075
SI            False        0.834080
              True         0.165920
Name: defuncion, dtype: float64

*¿Cuántos casos confirmados se tienen por Estado?*
> Para responder a esta pregunta, rescaté sólo los casos positivos y de ahí conté valores por entidad de residencia.

In [ ]:
### ¿Cuántos casos confirmados se tienen por Estado?
### Positivos por estado
data[data.resultado == 'Positivo SARS-CoV-2'].entidad_res.value_counts()

CIUDAD DE MÉXICO                   107613
MÉXICO                              71994
GUANAJUATO                          35182
NUEVO LEÓN                          32317
VERACRUZ DE IGNACIO DE LA LLAVE     30077
TABASCO                             29601
PUEBLA                              28426
TAMAULIPAS                          26159
COAHUILA DE ZARAGOZA                23440
SONORA                              22601
JALISCO                             22369
SAN LUIS POTOSÍ                     20000
BAJA CALIFORNIA                     17870
SINALOA                             16996
MICHOACÁN DE OCAMPO                 16840
YUCATÁN                             16013
GUERRERO                            15950
OAXACA                              14499
HIDALGO                             11113
QUINTANA ROO                        10872
CHIHUAHUA                            8663
BAJA CALIFORNIA SUR                  8529
QUERÉTARO                            7298
DURANGO                              7295
TLAXCALA                             6751
CHIAPAS                              6341
AGUASCALIENTES                       6147
ZACATECAS                            6017
CAMPECHE                             5744
MORELOS                              5442
NAYARIT                              5312
COLIMA                               4036
Name: entidad_res, dtype: int64

*¿Cuántas defunciones se tienen por Estado?*

>Para esta pregunta, rescato los casos de defunción True y cuento los valores por cada estado.

In [ ]:
### ¿Cuántas defunciones se tienen por Estado?
### Contar defunciones por estado
data[data.defuncion == True].entidad_res.value_counts()

MÉXICO                             13397
CIUDAD DE MÉXICO                   11860
VERACRUZ DE IGNACIO DE LA LLAVE     4750
PUEBLA                              4548
BAJA CALIFORNIA                     4034
JALISCO                             3789
SINALOA                             3672
NUEVO LEÓN                          3435
SONORA                              3248
GUANAJUATO                          2992
TABASCO                             2915
TAMAULIPAS                          2801
GUERRERO                            2252
COAHUILA DE ZARAGOZA                2097
HIDALGO                             2027
CHIHUAHUA                           1995
QUINTANA ROO                        1887
MICHOACÁN DE OCAMPO                 1860
YUCATÁN                             1774
SAN LUIS POTOSÍ                     1714
OAXACA                              1600
TLAXCALA                            1318
MORELOS                             1243
CHIAPAS                             1219
QUERÉTARO                            956
CAMPECHE                             954
NAYARIT                              804
ZACATECAS                            738
DURANGO                              701
COLIMA                               578
AGUASCALIENTES                       558
BAJA CALIFORNIA SUR                  514
Name: entidad_res, dtype: int64

*¿Cuántos fallecimientos han ocurrido en los pacientes Ambulatorios?*

>Para esta pregunta, como en la anterior, rescato los casos de defunción True, luego cuento por tipo de paciente.

In [ ]:
### ¿Cuántos fallecimientos han ocurrido en los pacientes Ambulatorios?
### Contar tipo de paciente y muertos
data[data.defuncion == True].tipo_paciente.value_counts()

HOSPITALIZADO    78823
AMBULATORIO       9407
Name: tipo_paciente, dtype: int64